### PR TITLE
fix #35, content-type charset handling bug

### LINKED ISSUE #35: Requests on node.js fail when content-type / charset header is missing.
Turns out that the js-side parser blows up when no content-type header is provided, such as below. I haven't figured out how to make express produce such output in the tests, but this is the default you'll get using play with a simple BadRequest() response. 

```
HTTP/1.1 404 Not Found
Request-Time: 82
Content-Length: 0
Date: Sun, 14 Aug 2016 20:50:46 GMT
```

The stack trace looks like this:

```
[info]   java.nio.charset.UnsupportedCharsetException: binary
[info]   at $c_Ljava_nio_charset_UnsupportedCharsetException.$c_jl_Throwable.fillInStackTrace__jl_Throwable(/Users/erik/Projects/telepath-play/src/shared/client/.js/target/scala-2.11/https:/raw.githubusercontent.com/scala-js/scala-js/v0.6.11/library/src/main/scala/scala/scalajs/runtime/StackTrace.scala:33:5)
[info]   at $c_Ljava_nio_charset_UnsupportedCharsetException.$c_jl_Throwable.init___T__jl_Throwable(/Users/erik/Projects/telepath-play/src/shared/client/.js/target/scala-2.11/https:/raw.githubusercontent.com/scala-js/scala-js/v0.6.11/javalanglib/src/main/scala/java/lang/Throwables.scala:12:19)
[info]   at java.nio.charset.UnsupportedCharsetException.<init>(/Users/erik/Projects/telepath-play/src/shared/client/.js/target/scala-2.11/https:/raw.githubusercontent.com/scala-js/scala-js/v0.6.11/javalib/src/main/scala/java/nio/charset/UnsupportedCharsetException.scala:4:34)
[info]   at java.nio.charset.Charset$.forName(/Users/erik/Projects/telepath-play/src/shared/client/.js/target/scala-2.11/https:/raw.githubusercontent.com/scala/scala/v2.11.8/src/library/scala/collection/MapLike.scala:128:10)
[info]   at scala.scalajs.runtime.RuntimeString$.newString(/Users/erik/Projects/telepath-play/src/shared/client/.js/target/scala-2.11/https:/raw.githubusercontent.com/scala-js/scala-js/v0.6.11/library/src/main/scala/scala/scalajs/runtime/RuntimeString.scala:316:14)
[info]   at fr.hmil.roshttp.HttpResponse.body$lzycompute(/Users/erik/Projects/telepath-play/src/shared/client/.js/target/scala-2.11/file:/Users/erik/Projects/telepath-play/vendor/RosHTTP/shared/src/main/scala/fr/hmil/roshttp/HttpResponse.scala:13:5)
[info]   at fr.hmil.roshttp.HttpResponse.body(/Users/erik/Projects/telepath-play/src/shared/client/.js/target/scala-2.11/file:/Users/erik/Projects/telepath-play/vendor/RosHTTP/shared/src/main/scala/fr/hmil/roshttp/HttpResponse.scala:12:12)
```

### PR DESCRIPTION
**Pull request by hmil**

### CODE REVIEW

File: shared/src/main/scala/fr/hmil/roshttp/tools/io/IO.scala [hunk 1]
```diff
@@ -75,13 +75,19 @@ private[roshttp] object IO {
 
     @tailrec
     def loop(): Unit = {
-      val size = in.read(buffer)
-      if (size > 0) {
-        out.write(buffer, 0, size)
-        loop()
-      }
+        val size = in.read(buffer)
```
Comment (sjrd) [inline shared/src/main/scala/fr/hmil/roshttp/tools/io/IO.scala]: You're introducing indentation issue here.

Comment (hmil) [reply shared/src/main/scala/fr/hmil/roshttp/tools/io/IO.scala]: nice catch!
